# Generated by Django 3.0.5 on 2020-05-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('can_edit_board', 'Edit Board Details'),)},
        ),
    ]
